// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9tBoI-2SiR4v4dbRI5n_UZ0w3flWJiFg',
    appId: '1:208379803297:web:8d293d95a0d415f5cbe2e0',
    messagingSenderId: '208379803297',
    projectId: 'flash-chat-b2663',
    authDomain: 'flash-chat-b2663.firebaseapp.com',
    storageBucket: 'flash-chat-b2663.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE2Wc9KOQmViOEuL9C3Xzi64V4-yvB1ls',
    appId: '1:208379803297:android:4e2b9a9d1ea16bcdcbe2e0',
    messagingSenderId: '208379803297',
    projectId: 'flash-chat-b2663',
    storageBucket: 'flash-chat-b2663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJM5CWtM1ualtltdUaLeEaS6P310WA4k',
    appId: '1:208379803297:ios:127b962923894eb6cbe2e0',
    messagingSenderId: '208379803297',
    projectId: 'flash-chat-b2663',
    storageBucket: 'flash-chat-b2663.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzJM5CWtM1ualtltdUaLeEaS6P310WA4k',
    appId: '1:208379803297:ios:64944a0e3fa5f39ccbe2e0',
    messagingSenderId: '208379803297',
    projectId: 'flash-chat-b2663',
    storageBucket: 'flash-chat-b2663.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
